### Soal Tipe Data

In [27]:
# data

company_name_list = [{'name': 'Company 1'},
          {'name': 'Company 2'},
          {'name': 'Company 3'}]

employee_name_list = [{'name': 'John Doe'},
          {'name': 'Tom Smith'},
          {'name': 'Andrew Sebastian'}]

company_detail_list = {
      'Company 1': {
          'name': 'Company 1',
          'domain': 'Retail',
          'clients': [
              {
                  'name': 'acme.inc',
                  'country': 'united states'
              },
              {
                  'name': 'Wayne.co',
                  'country': 'united states'
              }
          ]
      },
      'Company 2': {
          'name': 'Company 2',
          'domain': 'Construction',
          'clients': [
              {
                  'name': 'Tesla',
                  'country': 'united states'
              },
              {
                  'name': 'Japan Airlines',
                  'country': 'japan'
              },
              {
                  'name': 'Indofood',
                  'country': 'indonesia'
              }
          ]
      },
      'Company 3': {
          'name': 'Company 3',
          'domain': 'Healthcare',
          'clients': [
              {
                  'name': 'Petronas',
                  'country': 'malaysia'
              },
              {
                  'name': 'VW Group',
                  'country': 'germany'
              },
              {
                  'name': 'IBM',
                  'country': 'united states'
              },
              {
                  'name': 'Mitsubishi',
                  'country': 'japan'
              }
          ]
      }
  }

employee_detail_list = {
      'John Doe': {
          'name': 'EMP-0001',
          'first_name': 'John',
          'last_name': 'Doe',
          'full_name': 'John Doe',
          'company': 'Company 1'
      },
      'Tom Smith': {
          'name': 'EMP-0002',
          'first_name': 'Tom',
          'last_name': 'Smith',
          'full_name': 'Tom Smith',
          'company': 'Company 2'
      },
      'Andrew Sebastian': {
          'name': 'EMP-0003',
          'first_name': 'Andrew',
          'last_name': 'Sebastian',
          'full_name': 'Andrew Sebastian',
          'company': 'Company 2'
      },
  }

#### Petunjuk:
Dari data di atas kerjakan soal di bawah untuk nomor **1 - 4**, sebisa mungkin gunakan comprehension loop apabila ada perulangan:

### 1 
Please get the list of all Companies and sort by **Company Domain** in reverse order.

Expected result:


```json
[{
    "name": "Company 1", 
    "domain": "Retail"
}, {
    "name": "Company 3", 
    "domain": "Healthcare"
}, {
    "name": "Company 2", 
    "domain": "Construction"
}]
```

In [76]:
def sort_company():
    company_detail_list = {
        'Company 1': {
            'name': 'Company 1',
            'domain': 'Retail',
            'clients': [
                {
                    'name': 'acme.inc',
                    'country': 'united states'
                },
                {
                    'name': 'Wayne.co',
                    'country': 'united states'
                }
            ]
        },
        'Company 2': {
            'name': 'Company 2',
            'domain': 'Construction',
            'clients': [
                {
                    'name': 'Tesla',
                    'country': 'united states'
                },
                {
                    'name': 'Japan Airlines',
                    'country': 'japan'
                },
                {
                    'name': 'Indofood',
                    'country': 'indonesia'
                }
            ]
        },
        'Company 3': {
            'name': 'Company 3',
            'domain': 'Healthcare',
            'clients': [
                {
                    'name': 'Petronas',
                    'country': 'malaysia'
                },
                {
                    'name': 'VW Group',
                    'country': 'germany'
                },
                {
                    'name': 'IBM',
                    'country': 'united states'
                },
                {
                    'name': 'Mitsubishi',
                    'country': 'japan'
                }
            ]
        }
    }

    sorted_companies = []
    for company in company_detail_list.values():
        sorted_companies.append({
            'name': company['name'],
            'domain': company['domain']
        })

    print(sorted_companies)

sort_company()
pass

[{'name': 'Company 1', 'domain': 'Retail'}, {'name': 'Company 2', 'domain': 'Construction'}, {'name': 'Company 3', 'domain': 'Healthcare'}]

### 2
Please print all Domain value in every company.

Expected return:

```
Company 1: Retail, relation: 2 clients
Company 2: Construction, relation: 3 clients
Company 3: Healthcare, relation: 4 clients
```

In [94]:
# lengkapi function berikut
def get_company_domain():
    company_detail_list = {
        'Company 1': {
            'name': 'Company 1',
            'domain': 'Retail',
            'clients': [
                {
                    'name': 'acme.inc',
                    'country': 'united states'
                },
                {
                    'name': 'Wayne.co',
                    'country': 'united states'
                }
            ]
        },
        'Company 2': {
            'name': 'Company 2',
            'domain': 'Construction',
            'clients': [
                {
                    'name': 'Tesla',
                    'country': 'united states'
                },
                {
                    'name': 'Japan Airlines',
                    'country': 'japan'
                },
                {
                    'name': 'Indofood',
                    'country': 'indonesia'
                }
            ]
        },
        'Company 3': {
            'name': 'Company 3',
            'domain': 'Healthcare',
            'clients': [
                {
                    'name': 'Petronas',
                    'country': 'malaysia'
                },
                {
                    'name': 'VW Group',
                    'country': 'germany'
                },
                {
                    'name': 'IBM',
                    'country': 'united states'
                },
                {
                    'name': 'Mitsubishi',
                    'country': 'japan'
                }
            ]
        }
    }

    sorted_companies = []
    for company in company_detail_list.values():
        sorted_companies.append({
            'name': company['name'],
            'domain': company['domain'],
            'clients': len(company['clients'])
        })

    for company in sorted_companies:
        print(f"{company['name']}: {company['domain']}, relation: {company['clients']} clients")

get_company_domain()
pass

Company 1: Retail, relation: 2 clients
Company 2: Construction, relation: 3 clients
Company 3: Healthcare, relation: 4 clients

### 3
Create a function that return employees with it's company domain.

Expected return:


```json
[{
    "full_name": "John Doe",
    "company": "Company 1",
    "domain": "Retail"
}, {
    "full_name": "Tom Smith",
    "company": "Company 2",
    "domain": "Construction"
}, {
    "full_name": "Andrew Sebastian",
    "company": "Company 2",
    "domain": "Construction"
}]
```

In [120]:
# lengkapi function berikut
def get_employees():
    company_detail_list = {
        'Company 1': {
            'name': 'Company 1',
            'domain': 'Retail',
            'clients': [
                {
                    'name': 'acme.inc',
                    'country': 'united states'
                },
                {
                    'name': 'Wayne.co',
                    'country': 'united states'
                }
            ]
        },
        'Company 2': {
            'name': 'Company 2',
            'domain': 'Construction',
            'clients': [
                {
                    'name': 'Tesla',
                    'country': 'united states'
                },
                {
                    'name': 'Japan Airlines',
                    'country': 'japan'
                },
                {
                    'name': 'Indofood',
                    'country': 'indonesia'
                }
            ]
        },
        'Company 3': {
            'name': 'Company 3',
            'domain': 'Healthcare',
            'clients': [
                {
                    'name': 'Petronas',
                    'country': 'malaysia'
                },
                {
                    'name': 'VW Group',
                    'country': 'germany'
                },
                {
                    'name': 'IBM',
                    'country': 'united states'
                },
                {
                    'name': 'Mitsubishi',
                    'country': 'japan'
                }
            ]
        }
    }

    employee_detail_list = {
        'John Doe': {
            'name': 'EMP-0001',
            'first_name': 'John',
            'last_name': 'Doe',
            'full_name': 'John Doe',
            'company': 'Company 1'
        },
        'Tom Smith': {
            'name': 'EMP-0002',
            'first_name': 'Tom',
            'last_name': 'Smith',
            'full_name': 'Tom Smith',
            'company': 'Company 2'
        },
        'Andrew Sebastian': {
            'name': 'EMP-0003',
            'first_name': 'Andrew',
            'last_name': 'Sebastian',
            'full_name': 'Andrew Sebastian',
            'company': 'Company 2'
        },
    }

    result_employee = []

    for employee in employee_detail_list.values():
        company_name = employee['company']
        domain = company_detail_list[company_name]['domain']
        result_employee.append({
            "full_name": employee['full_name'],
            "company": company_name,
            "domain": domain
        })

    return result_employee

employee_domain_list = get_employees()

for entry in employee_domain_list:
    print(entry)

pass

{'full_name': 'John Doe', 'company': 'Company 1', 'domain': 'Retail'}
{'full_name': 'Tom Smith', 'company': 'Company 2', 'domain': 'Construction'}
{'full_name': 'Andrew Sebastian', 'company': 'Company 2', 'domain': 'Construction'}

### 4
Create a function that return companies with list of employees that are working in the company.

Expected return:


```json
[{
    "company": "Company 1",
    "employees": ["John Doe"]
}, {
    "company": "Company 2",
    "employees": ["Tom Smith", "Andrew Sebastian"]
}, {
    "company": "Company 3",
    "employees": []
}]
```

In [130]:
# lengkapi function berikut
def get_employees_by_company():
    company_detail_list = {
        'Company 1': {
            'name': 'Company 1',
            'domain': 'Retail',
            'clients': [
                {
                    'name': 'acme.inc',
                    'country': 'united states'
                },
                {
                    'name': 'Wayne.co',
                    'country': 'united states'
                }
            ]
        },
        'Company 2': {
            'name': 'Company 2',
            'domain': 'Construction',
            'clients': [
                {
                    'name': 'Tesla',
                    'country': 'united states'
                },
                {
                    'name': 'Japan Airlines',
                    'country': 'japan'
                },
                {
                    'name': 'Indofood',
                    'country': 'indonesia'
                }
            ]
        },
        'Company 3': {
            'name': 'Company 3',
            'domain': 'Healthcare',
            'clients': [
                {
                    'name': 'Petronas',
                    'country': 'malaysia'
                },
                {
                    'name': 'VW Group',
                    'country': 'germany'
                },
                {
                    'name': 'IBM',
                    'country': 'united states'
                },
                {
                    'name': 'Mitsubishi',
                    'country': 'japan'
                }
            ]
        }
    }

    employee_detail_list = {
        'John Doe': {
            'name': 'EMP-0001',
            'first_name': 'John',
            'last_name': 'Doe',
            'full_name': 'John Doe',
            'company': 'Company 1'
        },
        'Tom Smith': {
            'name': 'EMP-0002',
            'first_name': 'Tom',
            'last_name': 'Smith',
            'full_name': 'Tom Smith',
            'company': 'Company 2'
        },
        'Andrew Sebastian': {
            'name': 'EMP-0003',
            'first_name': 'Andrew',
            'last_name': 'Sebastian',
            'full_name': 'Andrew Sebastian',
            'company': 'Company 2'
        },
    }

    company_employees = {company: [] for company in company_detail_list.keys()}

    for employee in employee_detail_list.values():
        company_name = employee['company']
        company_employees[company_name].append(employee['full_name'])

    result_employee = []
    for company, employees in company_employees.items():
        result_employee.append({
            "company": company,
            "employees": employees
        })

    return result_employee

company_employee_list = get_employees_by_company()

for entry in company_employee_list:
    print(entry)

{'company': 'Company 1', 'employees': ['John Doe']}
{'company': 'Company 2', 'employees': ['Tom Smith', 'Andrew Sebastian']}
{'company': 'Company 3', 'employees': []}

### Soal pre-processing data

In [134]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
import numpy as np

In [135]:
data_startup = pd.read_csv('50_Startups.csv')

In [140]:
data_startup.sample(7)
missing_data = data_startup.isnull().sum()
print("Data kosong:\n", missing_data)

# Mengisi data kosong dengan nilai mean
imputer = SimpleImputer(strategy='mean')
data_startup[['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']] = imputer.fit_transform(data_startup[['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']])

# One-hot encoding untuk kolom State
onehot_encoder = OneHotEncoder()
state_encoded = onehot_encoder.fit_transform(data_startup[['State']])
state_encoded_df = pd.DataFrame(state_encoded.toarray(), columns=onehot_encoder.get_feature_names_out(['State']))
data_startup = pd.concat([data_startup, state_encoded_df], axis=1)
data_startup.drop('State', axis=1, inplace=True)

# Membuat kolom baru Tax
data_startup['Tax'] = (data_startup['Profit'] + data_startup['Marketing Spend'] + data_startup['Administration']) * 0.05

# StandardScaler untuk semua fitur kecuali Profit
scaler = StandardScaler()
features_to_scale = [col for col in data_startup.columns if col != 'Profit']
data_startup[features_to_scale] = scaler.fit_transform(data_startup[features_to_scale])

# Menampilkan data setelah preprocessing
print("Data setelah preprocessing:\n", data_startup.head())

Data kosong:
 R&D Spend          5
Administration     3
Marketing Spend    5
State              0
Profit             2
dtype: int64
Data setelah preprocessing:
    R&D Spend  Administration  Marketing Spend     Profit  State_California  \
0   2.076351        0.554318         2.299248  192261.83         -0.717741
1   2.011840        1.123258         2.040926  191792.06          1.393261
2   1.797168       -0.850460         1.707769  191050.39         -0.717741
3   1.584537       -0.161817         1.478634  182901.99         -0.717741
4   1.531431       -1.233706         1.320863  166187.94         -0.717741

   State_Florida  State_New York       Tax
0      -0.685994        1.393261  2.460946
1      -0.685994       -0.717741  2.361311
2       1.457738       -0.717741  1.737043
3      -0.685994        1.393261  1.626770
4       1.457738       -0.717741  1.188570

### Soal
Dari data di atas lakukan pre-processing sbb:
1. Lakukan analisa mengenai field mana saja yang memiliki data kosong(Nan) lalu Isi data yang kosong tersebut menggunakan nilai mean
2. lakukan oneHotEncoder ke field state
3. buat field baru yaitu Tax. dimana Tax = (profit + Marketing Spend + administration) * 5%
4. Jalankan standardScaler field-field tersebut

### Ketentuan dan Deadline

1. Buat masing-masing repositori di github account
2. Soal dikerjakan di repositori tsb.
3. Jawaban yang dikumpulkan di **e-learning** merupakan link github dari repositori di atas.
4. Deadline pengumpulan soal adalah hari rabu, 15 Mei 2024 pukul 23:59.